import requests
import json

class Ckan:
    def __init__(self, url, api_key):
        self.url = url
        self.api_key = api_key
    
    def upsert_situations(self, resource_id, situations):
        # Don't know how to this properly in Python
        payload = '{"records": ['

        for i in range(0, len(situations)):
            payload += situations[i].to_json()
            if i < len(situations) - 1:
                payload += ","
        
        payload += '], "force": true, "method": "upsert", "resource_id": "' + resource_id + '"}'

        # urllib wants to POST bytes, but payload is a string. Used the code generated by Postman. 
        headers = {
            'Authorization': self.api_key,
            'Content-Type': 'application/json'
        }

        response = requests.request(
            "POST", 
            self.url + '/api/3/action/datastore_upsert', 
            headers=headers, 
            data=payload
        )

        json_response = json.loads(response.text)
        if json_response['success']:
            print('Situations successfully upserted to CKAN [{}]'.format(self.url))
        else: 
            print('Error upserting situations to CKAN [{}]: {}'.format(self.url, json_response['error']['message']))
